# Generated by Django 3.2.6 on 2021-08-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('snippet', models.TextField()),
                ('date_published', models.CharField(max_length=255)),
            ],
        ),
    ]
